apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    service: ratings
    app: ratings
    version: v1
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: ratings

