apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    service: user
    app: user
    version: v1
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: user
