---
# Source: grafana/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: grafana-6.16.3
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "8.1.2"
    app.kubernetes.io/managed-by: Helm
  name: grafana
  namespace: istio-system
---
# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: istio-system
  labels:
    helm.sh/chart: grafana-6.16.3
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "8.1.2"
    app.kubernetes.io/managed-by: Helm
data:
  plugins: servicenow-optimiz-grafana, novatec-sdg-panel
  grafana.ini: |-
    analytics:
      check_for_updates: true
    log:
      mode: console
    paths:
      data: /var/lib/grafana/data
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    plugins:
      allow_loading_unsigned_plugins: servicenow-optimiz-plugin, novatec-sdg-panel
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090
      access: proxy
      jsonData:
        timeInterval: 5s
      editable: true
      orgId: 1
    - name: servicenow-optimiz-plugin
      type: servicenow-optimiz-plugin
      url: https://itomvision2demo.service-now.com/api/snc/grafana_api
      access: proxy
      basicAuth: true
      basicAuthUser: optimiz
      withCredentials: true
      secureJsonData:
        basicAuthPassword: Optimiz123
      isDefault: true
      editable: true
  dashboards.yaml: |-
    apiVersion: 1
    providers:
    - name: 'servicenow-optimiz-provider'
      orgId: 1
      type: file
      disableDeletion: false
      updateIntervalSeconds: 120
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards
        foldersFromFilesStructure: true
---
# Source: grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: istio-system
  labels:
    helm.sh/chart: grafana-6.16.3
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "8.1.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer 
  ports:
    - name: service
      port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30000
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
---
# Source: grafana/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: istio-system
  labels:
    helm.sh/chart: grafana-6.16.3
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "8.1.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: grafana
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/instance: grafana
        app: grafana
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: grafana
      securityContext:
        fsGroup: 472
        runAsGroup: 472
        runAsUser: 472
      containers:
        - name: grafana
          image: "grafana/grafana:8.1.2"
          imagePullPolicy: IfNotPresent
          ports:
            - name: service
              containerPort: 3000
              protocol: TCP
            - name: grafana
              containerPort: 3000
              protocol: TCP
          env:
            - name: "GF_AUTH_ANONYMOUS_ENABLED"
              value: "true"
            - name: "GF_AUTH_ANONYMOUS_ORG_ROLE"
              value: "Admin"
            - name: "GF_AUTH_BASIC_ENABLED"
              value: "false"
            - name: "GF_SECURITY_ADMIN_PASSWORD"
              value: "-"
            - name: "GF_SECURITY_ADMIN_USER"
              value: "-"
            - name: "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS"
              value: "servicenow-optimiz-plugin, novatec-sdg-panel"
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
          volumeMounts:
            - name: config
              mountPath: "/etc/grafana/grafana.ini"
              subPath: grafana.ini
            - name: config
              mountPath: "/etc/grafana/provisioning/datasources/datasources.yaml"
              subPath: datasources.yaml
            - name: config
              mountPath: "/etc/grafana/provisioning/dashboards/dashboards.yaml"
              subPath: dashboards.yaml
            - name: servicenow-optimiz-plugin
              mountPath: "/var/lib/grafana/plugins/servicenow-optimiz-plugin"
            - name: novatec-sdg-panel
              mountPath: "/var/lib/grafana/plugins/novatec-sdg-panel"
            - name: dashboards
              mountPath: "/var/lib/grafana/dashboards"
      volumes:
        - name: config
          configMap:
            name: grafana
        - name: servicenow-optimiz-plugin
          hostPath:
            path: /home/ec2-user/git/servicenow-optimiz-plugin
            type: Directory
        - name: novatec-sdg-panel
          hostPath:
            path: /home/ec2-user/git/novatec-sdg-panel
            type: Directory
        - name: dashboards
          hostPath:
            path: /home/ec2-user/git/dashboards
            type: Directory
