name: Integration Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          # Must use at least depth 2!
          fetch-depth: 2

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-rc.1

      - name: Install Chaos Mesh
        run: |
          export CLUSTER="chart-testing"
          hack/local-up-chaos-mesh.sh
          kubectl set env deployment/chaos-dashboard SECURITY_MODE=true -n chaos-testing
          sleep 5
          kubectl port-forward -n chaos-testing svc/chaos-dashboard 2333:2333 &

      - name: Run integration test
        run: |
          bash test/integration_test/run.sh
