apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: jvm-exception-example
  namespace: app
spec:
  action: tce
  target: jvm
  flags:
    exception: "java.lang.Exception"
  matchers:
    classname: "org.chaosmesh.jvm.Application"
    methodname: "hello"
  mode: one
  selector:
    labelSelectors:
      app: springboot-jvmchaos-demo
  duration: "30s"
  scheduler:
    cron: "@every 1m"
