apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: jvm-oom-example
  namespace: app
spec:
  action: oom
  target: jvm
  flags:
    area: "HEAP"
    wild-mode: "true"
  mode: one
  selector:
    labelSelectors:
      app: springboot-jvmchaos-demo
  duration: "30s"
  scheduler:
    cron: "@every 1m"
