apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: jvm-delay4servlet-example
  namespace: app
spec:
  action: delay
  target: servlet
  flags:
    time: "10000"
  mode: one
  selector:
    labelSelectors:
      app: springboot-jvmchaos-demo
  duration: "50s"
  scheduler:
    cron: "@every 1m"
