kind: ConfigMap
apiVersion: v1
metadata:
  name: jvmchaos-sidecar
  namespace: app
  labels:
    app.kubernetes.io/component: webhook
data:
  jvmchaos-sidecar: |
    name: jvmchaos-sidecar
    selector:
      labelSelectors:
        "app": "springboot-jvmchaos-demo"
    template: jvmchaos-sidecar-template
