apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: logging
  labels:
    k8s-app: filebeat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
  # namespace: logging
  labels:
    k8s-app: filebeat
rules:
- apiGroups: [""] # "" indicates the core API group
    #- '*'
  resources:
    #- '*'
    - namespaces
    - pods
    - nodes
  verbs:
    #- '*'
    - get
    - watch
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
  # namespace: logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: filebeat
subjects:
#- kind: ServiceAccount
#  name: filebeat
#  namespace: default
- kind: ServiceAccount
  name: filebeat
  namespace: logging #kube-system
#- kind: ServiceAccount
#  name: filebeat
#  namespace: istio-system
